### ISSUE TITLE
Related posts snippet

### ISSUE THREAD

**Issue by anmonteiro** [mdo/jekyll-snippets#7]
Would you be interested in the addition of a related posts snippet to this repo?
It works by showing recent posts which contain the same tag/category as the current post, and when there are no more, just outputs links to any recent posts (as in jekyll's standard behaviour)

**Comment by mdo** [comment]
Like https://github.com/mdo/jekyll-snippets/blob/master/posts-related.html?

**Comment by mdo** [comment]
Oh, I see, maybe by category and tag then? If so, sure!

**Comment by anmonteiro** [comment]
Submitted in #8.
